// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: proto/config.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigStream_Subscribe_FullMethodName = "/dynoconf.v1.ConfigStream/Subscribe"
)

// ConfigStreamClient is the client API for ConfigStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigStream is the streaming contract consumed by applications.
//
// An application opens a single server-streaming RPC, identifies itself with
// its service_key, and (optionally) asks for a full snapshot of its current
// variables. The server then keeps the stream open and pushes incremental
// changes plus periodic heartbeats until the client disconnects or the server
// drains on shutdown.
type ConfigStreamClient interface {
	// Subscribe opens the stream. The server first sends a Snapshot (when
	// send_snapshot=true), then a continuous flow of Change events and
	// Heartbeats.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigEvent], error)
}

type configStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigStreamClient(cc grpc.ClientConnInterface) ConfigStreamClient {
	return &configStreamClient{cc}
}

func (c *configStreamClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigStream_ServiceDesc.Streams[0], ConfigStream_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ConfigEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigStream_SubscribeClient = grpc.ServerStreamingClient[ConfigEvent]

// ConfigStreamServer is the server API for ConfigStream service.
// All implementations must embed UnimplementedConfigStreamServer
// for forward compatibility.
//
// ConfigStream is the streaming contract consumed by applications.
//
// An application opens a single server-streaming RPC, identifies itself with
// its service_key, and (optionally) asks for a full snapshot of its current
// variables. The server then keeps the stream open and pushes incremental
// changes plus periodic heartbeats until the client disconnects or the server
// drains on shutdown.
type ConfigStreamServer interface {
	// Subscribe opens the stream. The server first sends a Snapshot (when
	// send_snapshot=true), then a continuous flow of Change events and
	// Heartbeats.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[ConfigEvent]) error
	mustEmbedUnimplementedConfigStreamServer()
}

// UnimplementedConfigStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigStreamServer struct{}

func (UnimplementedConfigStreamServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[ConfigEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedConfigStreamServer) mustEmbedUnimplementedConfigStreamServer() {}
func (UnimplementedConfigStreamServer) testEmbeddedByValue()                      {}

// UnsafeConfigStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigStreamServer will
// result in compilation errors.
type UnsafeConfigStreamServer interface {
	mustEmbedUnimplementedConfigStreamServer()
}

func RegisterConfigStreamServer(s grpc.ServiceRegistrar, srv ConfigStreamServer) {
	// If the following call panics, it indicates UnimplementedConfigStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigStream_ServiceDesc, srv)
}

func _ConfigStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigStreamServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, ConfigEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigStream_SubscribeServer = grpc.ServerStreamingServer[ConfigEvent]

// ConfigStream_ServiceDesc is the grpc.ServiceDesc for ConfigStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynoconf.v1.ConfigStream",
	HandlerType: (*ConfigStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ConfigStream_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/config.proto",
}
