// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/config.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Change_Type int32

const (
	Change_UPSERT Change_Type = 0
	Change_DELETE Change_Type = 1
)

// Enum value maps for Change_Type.
var (
	Change_Type_name = map[int32]string{
		0: "UPSERT",
		1: "DELETE",
	}
	Change_Type_value = map[string]int32{
		"UPSERT": 0,
		"DELETE": 1,
	}
)

func (x Change_Type) Enum() *Change_Type {
	p := new(Change_Type)
	*p = x
	return p
}

func (x Change_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Change_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_config_proto_enumTypes[0].Descriptor()
}

func (Change_Type) Type() protoreflect.EnumType {
	return &file_proto_config_proto_enumTypes[0]
}

func (x Change_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Change_Type.Descriptor instead.
func (Change_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{3, 0}
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// service_key identifies the logical service (see the `services` table).
	ServiceKey string `protobuf:"bytes,1,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	// send_snapshot asks the server to emit the full current set of variables
	// before streaming incremental changes. "Ready to accept all initial vars."
	SendSnapshot bool `protobuf:"varint,2,opt,name=send_snapshot,json=sendSnapshot,proto3" json:"send_snapshot,omitempty"`
	// client_token is RESERVED for a future per-service auth token. In v1 the
	// gRPC endpoint is network-restricted and this field is NOT validated.
	ClientToken   string `protobuf:"bytes,3,opt,name=client_token,json=clientToken,proto3" json:"client_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *SubscribeRequest) GetSendSnapshot() bool {
	if x != nil {
		return x.SendSnapshot
	}
	return false
}

func (x *SubscribeRequest) GetClientToken() string {
	if x != nil {
		return x.ClientToken
	}
	return ""
}

type ConfigEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ConfigEvent_Snapshot
	//	*ConfigEvent_Change
	//	*ConfigEvent_Heartbeat
	Event         isConfigEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEvent) Reset() {
	*x = ConfigEvent{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEvent) ProtoMessage() {}

func (x *ConfigEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEvent.ProtoReflect.Descriptor instead.
func (*ConfigEvent) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigEvent) GetEvent() isConfigEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ConfigEvent) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Event.(*ConfigEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ConfigEvent) GetChange() *Change {
	if x != nil {
		if x, ok := x.Event.(*ConfigEvent_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *ConfigEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*ConfigEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isConfigEvent_Event interface {
	isConfigEvent_Event()
}

type ConfigEvent_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // all current variables of the service
}

type ConfigEvent_Change struct {
	Change *Change `protobuf:"bytes,2,opt,name=change,proto3,oneof"` // a single incremental change
}

type ConfigEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // liveness ping
}

func (*ConfigEvent_Snapshot) isConfigEvent_Event() {}

func (*ConfigEvent_Change) isConfigEvent_Event() {}

func (*ConfigEvent_Heartbeat) isConfigEvent_Event() {}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     []*Variable            `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetVariables() []*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Change_Type            `protobuf:"varint,1,opt,name=type,proto3,enum=dynoconf.v1.Change_Type" json:"type,omitempty"`
	Variable      *Variable              `protobuf:"bytes,2,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *Change) GetType() Change_Type {
	if x != nil {
		return x.Type
	}
	return Change_UPSERT
}

func (x *Change) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *Variable) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Variable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Variable) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\vdynoconf.v1\"{\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vservice_key\x18\x01 \x01(\tR\n" +
	"serviceKey\x12#\n" +
	"\rsend_snapshot\x18\x02 \x01(\bR\fsendSnapshot\x12!\n" +
	"\fclient_token\x18\x03 \x01(\tR\vclientToken\"\xb2\x01\n" +
	"\vConfigEvent\x123\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x15.dynoconf.v1.SnapshotH\x00R\bsnapshot\x12-\n" +
	"\x06change\x18\x02 \x01(\v2\x13.dynoconf.v1.ChangeH\x00R\x06change\x126\n" +
	"\theartbeat\x18\x03 \x01(\v2\x16.dynoconf.v1.HeartbeatH\x00R\theartbeatB\a\n" +
	"\x05event\"?\n" +
	"\bSnapshot\x123\n" +
	"\tvariables\x18\x01 \x03(\v2\x15.dynoconf.v1.VariableR\tvariables\"\x89\x01\n" +
	"\x06Change\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.dynoconf.v1.Change.TypeR\x04type\x121\n" +
	"\bvariable\x18\x02 \x01(\v2\x15.dynoconf.v1.VariableR\bvariable\"\x1e\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\"L\n" +
	"\bVariable\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\x1b\n" +
	"\tHeartbeat\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts2V\n" +
	"\fConfigStream\x12F\n" +
	"\tSubscribe\x12\x1d.dynoconf.v1.SubscribeRequest\x1a\x18.dynoconf.v1.ConfigEvent0\x01B`\n" +
	"\vdynoconf.v1B\vConfigProtoP\x01ZBgithub.com/dynoconf/dynoconf/internal/grpcserver/configpb;configpbb\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_config_proto_goTypes = []any{
	(Change_Type)(0),         // 0: dynoconf.v1.Change.Type
	(*SubscribeRequest)(nil), // 1: dynoconf.v1.SubscribeRequest
	(*ConfigEvent)(nil),      // 2: dynoconf.v1.ConfigEvent
	(*Snapshot)(nil),         // 3: dynoconf.v1.Snapshot
	(*Change)(nil),           // 4: dynoconf.v1.Change
	(*Variable)(nil),         // 5: dynoconf.v1.Variable
	(*Heartbeat)(nil),        // 6: dynoconf.v1.Heartbeat
}
var file_proto_config_proto_depIdxs = []int32{
	3, // 0: dynoconf.v1.ConfigEvent.snapshot:type_name -> dynoconf.v1.Snapshot
	4, // 1: dynoconf.v1.ConfigEvent.change:type_name -> dynoconf.v1.Change
	6, // 2: dynoconf.v1.ConfigEvent.heartbeat:type_name -> dynoconf.v1.Heartbeat
	5, // 3: dynoconf.v1.Snapshot.variables:type_name -> dynoconf.v1.Variable
	0, // 4: dynoconf.v1.Change.type:type_name -> dynoconf.v1.Change.Type
	5, // 5: dynoconf.v1.Change.variable:type_name -> dynoconf.v1.Variable
	1, // 6: dynoconf.v1.ConfigStream.Subscribe:input_type -> dynoconf.v1.SubscribeRequest
	2, // 7: dynoconf.v1.ConfigStream.Subscribe:output_type -> dynoconf.v1.ConfigEvent
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	file_proto_config_proto_msgTypes[1].OneofWrappers = []any{
		(*ConfigEvent_Snapshot)(nil),
		(*ConfigEvent_Change)(nil),
		(*ConfigEvent_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		EnumInfos:         file_proto_config_proto_enumTypes,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
