{{- if and .Values.secret.create (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynoconf.fullname" . }}
  labels:
    {{- include "dynoconf.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  SESSION_SECRET: {{ .Values.secret.sessionSecret | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secret.oidcClientSecret | quote }}
{{- end }}
